# Generated by Django 5.2.2 on 2025-11-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_add_poster_and_tmdb_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tmdb_rating',
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='海报'),
        ),
    ]
