# Generated by Django 5.2.2 on 2025-11-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_film_poster_path_remove_film_tmdb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
    ]
